### ISSUE TITLE
Make Gamma Utils status effects more distinguishable from normal effects in the HUD

### ISSUE THREAD

**Issue by mrjasonn** [Sjouwer/gamma-utils#50] opened 2024-10-23 12:23 UTC
A way to do this could be adding a small Gamma Utils logo to the status effect icon to make it distinguishable. It is also important to make sure any normal status effects that Gamma Utils is showing will also show properly in the HUD if its set to show in the HUD.

**Comment by Sjouwer** [comment] 2024-11-17 17:41
The core of the issue is that GammaUtils uses the vanilla Night Vision instead of adding its own effect. This is why the icon is the same. Since you also made [another issue](https://github.com/Sjouwer/gamma-utils/issues/53) for that I'll be closing this one. For any futher discussion on this issue feel free to post it there.

**Closed as completed by Sjouwer** 2024-11-17 17:41 UTC
