### ISSUE TITLE
Add "Gamma Utils" to the name of Gamma Utils effects for better distinguishability between normal effects

### ISSUE THREAD

**Issue by mrjasonn** [Sjouwer/gamma-utils#49] opened 2024-10-23 12:19 UTC
This would be good as you might have night vision in the game and also have it on in Gamma Utils, and this would help distinguish between the normal status effects and Gamma Utils status effects. It is also important to make sure any normal status effects that Gamma Utils is showing will also show properly in the inventory. An example of this naming would be "Gamma Utils Night Vision" instead of just "Night Vision".

**Comment by Sjouwer** [comment] 2024-11-17 17:42
The core of the issue is that GammaUtils uses the vanilla Night Vision instead of adding its own effect. This is why the name is the same. Since you also made [another issue](https://github.com/Sjouwer/gamma-utils/issues/53) for that I'll be closing this one. For any futher discussion on this issue feel free to post it there.

**Closed as completed by Sjouwer** 2024-11-17 17:42 UTC
