### ISSUE TITLE
Fullbright not working and after uninstalling it, it still shows an error.

### ISSUE THREAD

**Issue by Airpodspro331** [Sjouwer/gamma-utils#55] opened 2024-10-30 09:50 UTC
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'fullbright_1.21' (fullbright_1_21) 1.0-SNAPSHOT with any version that is compatible with:
		 - fabricloader 0.16.7
		 - minecraft 1.21.1
More details:
	 - Mod 'fullbright_1.21' (fullbright_1_21) 1.0-SNAPSHOT requires version 0.16.8 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.16.7!
	 - Mod 'fullbright_1.21' (fullbright_1_21) 1.0-SNAPSHOT requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'Concurrent Chunk Management Engine (Optimizations/Natives Math)' (c2me-opts-natives-math) 0.3.0+alpha.0.293+1.21.1 requires version 22 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

This is the error.

I was trying to uninstall everything that is related to mod GammaUtills (Fullbright) and it still shows this.

I have fabric loader 0.16.8 and minecraft 1.21.1.

I think i tried most things that everyone would try.

If yall have suggestions, I am open to hear them :D.

**Comment by Sjouwer** [comment] 2024-10-30 13:49
Duplicate of https://github.com/Sjouwer/gamma-utils/issues/56

**Closed as completed by Sjouwer** 2024-10-30 13:49 UTC
