### ISSUE TITLE
Gamma-Utils-1.6.6-beta3-mc1.19 cant up to 1500%, max is only 100%

### ISSUE THREAD

**Issue by siyangfei** [Sjouwer/gamma-utils#9] opened 2022-04-24 17:05 UTC
Gamma-Utils-1.6.6-beta3-mc1.19 cant up to 1500%, max is only 100%

**Comment by Sjouwer** [comment] 2022-04-24 19:09
Hmm I do not experience that issue myself.
Which minecraft version do you play on?
Are there any other mods you are using?

**Comment by siyangfei** [comment] 2022-04-25 02:01
![image](https://user-images.githubusercontent.com/35626979/165008701-a8cfabb5-031d-4255-8e0d-1d3289f4c0de.png)

**Comment by siyangfei** [comment] 2022-04-25 02:02
and i use 22w16b

**Comment by Sjouwer** [comment] 2022-04-25 12:37
I installed all the same mods and still didn't encounter the issue.
How are you trying to adjust the gamma?

**Comment by siyangfei** [comment] 2022-04-25 12:56
thats strange,can you add me with QQ? 191198489

**Comment by siyangfei** [comment] 2022-04-25 12:58
1.18 version works fine,  but 1.19 not work, i adjust it by  press G, and  + -  to adjust it.

**Comment by Sjouwer** [comment] 2022-04-25 13:09
I'm sorry, I don't use QQ
I do have Discord if that helps: Sjouwer#3969

I know there was an issue with the first beta which sounds exactly like the one you're describing.
However I fixed that in the second beta

**Comment by Sjouwer** [comment] 2022-04-25 13:21
Could you maybe try deleting the gamma_utils.json5 config file and see if that helps

**Comment by Sjouwer** [comment] 2022-04-25 13:24
And if that doesn't help, would you be able to provide the latest log file?
It might contain a clue as to what's happening, maybe my mixin is failing for you somehow

**Comment by Sjouwer** [comment] 2022-04-25 14:02
Seems the issue was caused by me not using a translated key, is fixed now in beta 4

**Closed as completed by Sjouwer** 2022-04-25 14:02 UTC
